CREATE TABLE PASILLO(
PASILLO_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY ( PASILLO_ID ),
CONTORNO_ID INT NOT NULL,
CONSTRAINT FK_SCONTORNO_ID FOREIGN KEY (CONTORNO_ID) REFERENCES  CONTORNO(CONTORNO_ID)
);


CREATE TABLE EDIFICIO(
EDIFICIO_ID INT NOT NULL AUTO_INCREMENT,
primary key ( EDIFICIO_ID),
CLAVE VARCHAR(30) NOT NULL,
POLIGONO_ID INT NOT NULL,
CONSTRAINT FK_EPOLIGONO_ID foreign key (POLIGONO_ID) REFERENCES POLIGONO(POLIGONO_ID)
);


CREATE TABLE AVENIDA(
AVENIDA_ID INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY (AVENIDA_ID),
CLAVE VARCHAR(30) NOT NULL,
POLIGONO_ID INT NOT NULL,
CONSTRAINT FK_APOLIGONO_ID foreign key (POLIGONO_ID) REFERENCES POLIGONO(POLIGONO_ID)
);

CREATE TABLE AREA_VERDE(
AREA_VERDE_ID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (AREA_VERDE_ID),
CLAVE VARCHAR(30) NOT NULL,
POLIGONO_ID INT NOT NULL,
CONSTRAINT FK_AVPOLIGONO_ID foreign key (POLIGONO_ID) REFERENCES POLIGONO(POLIGONO_ID)
);

CREATE TABLE ESCUELA(
ESCUELA_ID INT NOT NULL auto_increment,
primary key (ESCUELA_ID),
CLAVE VARCHAR(30) NOT NULL,
POLIGONO_ID INT NOT NULL,
CONSTRAINT FK_ESPOLIGONO_ID foreign key (POLIGONO_ID) REFERENCES POLIGONO(POLIGONO_ID)
);

CREATE TABLE CENTRO_COMERICAL(
CENTRO_COMERCIAL_ID INT NOT NULL auto_increment,
PRIMARY KEY (CENTRO_COMERCIAL_ID),
CLAVE VARCHAR(30) NOT NULL,
POLIGONO_ID INT NOT NULL,
CONSTRAINT FK_CPOLIGONO_ID foreign key (POLIGONO_ID) REFERENCES POLIGONO(POLIGONO_ID)
);