INSERT INTO AVENIDA (AVENIDA_ID,CLAVE,POLIGONO_ID) VALUES (1,"AV. SUR", 13);
INSERT INTO AVENIDA (AVENIDA_ID,CLAVE,POLIGONO_ID) VALUES (2,"AV. PONIENTE", 18);
INSERT INTO AVENIDA (AVENIDA_ID,CLAVE,POLIGONO_ID) VALUES (3,"AV. NORTE", 16);
INSERT INTO AVENIDA (AVENIDA_ID,CLAVE,POLIGONO_ID) VALUES (4,"AV. MADERO", 17);
INSERT INTO AVENIDA (AVENIDA_ID,CLAVE,POLIGONO_ID) VALUES (5,"AV. JUAREZ", 14);
INSERT INTO AVENIDA (AVENIDA_ID,CLAVE,POLIGONO_ID) VALUES (6,"AV. CENTRAL", 15);