INSERT INTO AREA_VERDE (AREA_VERDE_ID,CLAVE,POLIGONO_ID) VALUES (1,	"A1" ,2);
INSERT INTO AREA_VERDE (AREA_VERDE_ID,CLAVE,POLIGONO_ID) VALUES (2,	"A2" ,1);
INSERT INTO AREA_VERDE (AREA_VERDE_ID,CLAVE,POLIGONO_ID) VALUES (3,	"A3" ,4);
INSERT INTO AREA_VERDE (AREA_VERDE_ID,CLAVE,POLIGONO_ID) VALUES (4,	"A4" ,5);
INSERT INTO AREA_VERDE (AREA_VERDE_ID,CLAVE,POLIGONO_ID) VALUES (5,	"A5" ,11);