INSERT INTO EDIFICIO (EDIFICIO_ID,CLAVE,POLIGONO_ID) VALUES (1,	"A"	,9);
INSERT INTO EDIFICIO (EDIFICIO_ID,CLAVE,POLIGONO_ID) VALUES (2,	"B"	,8);
INSERT INTO EDIFICIO (EDIFICIO_ID,CLAVE,POLIGONO_ID) VALUES (3,	"C"	,6);
INSERT INTO EDIFICIO (EDIFICIO_ID,CLAVE,POLIGONO_ID) VALUES (4,	"D"	,7);