INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (1, "EXTINGUIDOR A" ,60);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (2, "EXTINGUIDOR B" ,67);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (3, "CINE" ,64);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (4, "BAR" ,62);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (5, "RESTAURANTE" ,63);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (6, "SUPER" ,65);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (7, "CAFE" ,66);
INSERT INTO COMERCIO (COMERCIO_ID,CLAVE,PUNTO_ID) VALUES (8, "LIBRERIA" ,12);
